# SPDX-License-Identifier: Apache-2.0
# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: zephyr-dom0-xt

  remotes:
    - name: xentroops
      url-base: https://github.com/xen-troops/
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos/

  projects:
    - name: zephyr
      remote: xentroops
      revision: 87a14407f662ca997a3b60c58416e2c2a73ad0eb
      west-commands: scripts/west-commands.yml
    - name: zephyr-xenlib
      remote: xentroops
      revision: d563aadb0f16c1bf7ea08f171c3db288f503d1c8
    - name: fatfs
      remote: zephyrproject-rtos
      revision: f4ead3bf4a6dab3a07d7b5f5315795c073db568d
    - name: zephyr-xrun
      remote: xentroops
      revision: 5b6ecf274bac79b0be740693766a88d3eedf3b44
